### ISSUE TITLE
Problem with cloning this repository using git lfs

### ISSUE THREAD

**Issue by uysalelif** [SapienzaNLP/mwsd-datasets#2]
Hi,
I try to clone this repository using git lfs, but it gives the following error:

`batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

How can I download or clone this repository to access datasets and babelnet_mapping_4.0.jar file.

Thanks,

**Comment by pasinit** [comment]
Hi, sorry for the inconvenience. We temporary solved the issue by moving the data on google drive. You can now download them by following the link the in README.

Cheers, 
Tommaso
