### ISSUE TITLE
error downloading multilingual dataset

### ISSUE THREAD

**Issue by suytingwan** [SapienzaNLP/mwsd-datasets#3]
Hi, I try to download multilingual_wsd_all_v1.0.tar.gz, multilingual_wsd_wn_v1.0.tar.gz directly from google drive link but it failed to uncompress them. I also download directly from latest release m-wsd-datasets-v1.0 source code. However, the multilingual_wsd_all_v1.0.tar.gz multilingual_wsd_wn_v1.0.tar.gz are ASCII text. I use 'tar -xvf' but they can not be uncompressed. Is there anything wrong with the data or the way I process them? Can you please help me check the data?Thank you.

**Comment by pasinit** [comment]
Hi suytingwan, thanks for reporting this! I am sorry for the inconvenient. I should have fixed the links, could please try again and in case something is still wrong re-open this issue? 

Thanks!
