### ISSUE TITLE
Is the downloaded BabelNet_mapping_4.0.jar file correct?

### ISSUE THREAD

**Issue by suytingwan** [SapienzaNLP/mwsd-datasets#4]
Hi Pasinit, thank your for updating the multilingual datasets and I can now download the files. I have another question that the downloaded inventory_building/babelnet_mapping_4.0.jar is a text file (the size is only about 100K). I think I don't get the correct jar file which should be 113M. Can you please help check how to get the jar file?

**Comment by suytingwan** [comment]
<img width="1059" alt="截屏2020-12-09 下午11 42 43" src="https://user-images.githubusercontent.com/11863451/101651679-4bf89180-3a78-11eb-89df-42098e5370d9.png">


I use git lfs clone but it does not work.

**Comment by pasinit** [comment]
you right again, we have reached the limit so git lfs is not working anymore. I moved the data on Google drive. You can find the link on the homepage. Sorry for the incovenince.
